/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import view.Contrato;


        

/**
 *
 * @author alvaro
 */
public class OC extends javax.swing.JFrame {

    /**
     * Creates new form OC
     */
    public OC() {
        initComponents();
        TabelaOC.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        TabelaOC.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());

       TabelaOC.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        DefaultTableModel modelo = (DefaultTableModel) TabelaOC.getModel();
        TabelaOC.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    public void limparCampos(){
        TxtNumeroOC.setText("");
        TxtNumero.setText("");
        TxtCliente.setText("");
        TxtEndereco.setText("");
        TxtProduto.setText("");
        TxtStatus.setSelectedItem("Em Andamento");
        
    }
     public void readJTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) TabelaOC.getModel();
        modelo.setNumRows(0);
        orden_carregamento pdao = new orden_carregamento();
       
        for (OrdenCarregamento p : pdao.read()) {
        
            modelo.addRow(new Object[]{
            p.getId_oc(),
            p.getId_pedido(),
            p.getCliente(),
            p.getEndereco(),
            p.getProduto(),
            p.getStatus()
            
          
            
           
       });                       
    
        }
    }
        public void readJTableForDesc(String desc){
        DefaultTableModel modelo = (DefaultTableModel) TabelaOC.getModel();
        modelo.setNumRows(0);
        orden_carregamento pdao = new orden_carregamento();
       
        for (OrdenCarregamento p : pdao.readForDesc(desc)) {
        
            modelo.addRow(new Object[]{
            p.getId_oc(),
            p.getId_pedido(),
            p.getCliente(),
            p.getEndereco(),
            p.getProduto(),
            p.getStatus()
            
           
       });
    
    
    }
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        TxtStatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Baixar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaOC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TxtCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtProduto = new javax.swing.JTextPane();
        TxtEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtNumeroOC = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("N° Pedido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        TxtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroActionPerformed(evt);
            }
        });
        TxtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNumeroKeyPressed(evt);
            }
        });
        jPanel1.add(TxtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        TxtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Andamento", "Baixada", "Cancelada", " " }));
        jPanel1.add(TxtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 140, 30));

        jLabel3.setText("Status:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));

        jButton1.setBackground(new java.awt.Color(247, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setText("Excluir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        Baixar.setBackground(new java.awt.Color(0, 255, 51));
        Baixar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Baixar.setText("Baixar");
        Baixar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Baixar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 90, -1));

        jButton4.setBackground(new java.awt.Color(0, 51, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton4.setText("Adicionar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 110, -1));

        TabelaOC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº da Carga", "Nº do Pedido", "Cliente", "Endereço", "Produtos", "Status"
            }
        ));
        TabelaOC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaOCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaOC);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 930, 303));

        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));
        jPanel1.add(TxtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, 30));

        jLabel4.setText("Produtos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jScrollPane3.setViewportView(TxtProduto);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 172, 30));
        jPanel1.add(TxtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 170, 30));

        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        TxtNumeroOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroOCActionPerformed(evt);
            }
        });
        TxtNumeroOC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNumeroOCKeyPressed(evt);
            }
        });
        jPanel1.add(TxtNumeroOC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, 30));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setText("Alterar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jLabel6.setText("Nº da Carga / Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jButton6.setText("NOVO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNumeroOCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumeroOCKeyPressed
    if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        readJTableForDesc(TxtNumeroOC.getText());   
    }
    }//GEN-LAST:event_TxtNumeroOCKeyPressed

    private void TxtNumeroOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroOCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeroOCActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        OrdenCarregamento c = new OrdenCarregamento();
        orden_carregamento dao = new orden_carregamento();

        c.setId_pedido(TxtNumero.getText());
        c.setCliente(TxtCliente.getText());
        c.setEndereco(TxtEndereco.getText());
        c.setProduto(TxtProduto.getText());
        c.setStatus((String) TxtStatus.getSelectedItem());

        dao.create(c);
        readJTable();
        limparCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        readJTableForDesc(TxtNumeroOC.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumeroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                Connection con =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pontovenda","root","acessonery");
                PreparedStatement p = con.prepareStatement(" select * from vendas  WHERE numero_ven = ? ");

                p.setString(1 , TxtNumero.getText());

                ResultSet r = p.executeQuery();

                while (r.next()){
                    TxtNumero.setText(r.getString ("numero_ven"));
                    TxtCliente.setText(r.getString("cliente_vend"));
                    TxtEndereco.setText(r.getString("total_ven"));
                    TxtProduto.setText(r.getString("itens_vend"));

                }
            } catch (SQLException ex) {

                Logger.getLogger(OC.class.getName()).log(Level.SEVERE, null, ex);

            }

        }
    }//GEN-LAST:event_TxtNumeroKeyPressed

    private void TxtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroActionPerformed

    }//GEN-LAST:event_TxtNumeroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
        
        if  ( JOptionPane.showConfirmDialog(this, "Confirma?")==0)
              {
              
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pontovenda","root","acessonery");
            //Objeto para enviar comandos sql
            PreparedStatement p = con.prepareStatement("delete from carga where id = ?");
            //Envia o comando e guarda em um objeto ResultSet (Resultado)
            p.setString(1, TabelaOC.getValueAt(TabelaOC.getSelectedRow(), 0 ).toString() );
            p.execute();
                readJTable();
        
              JOptionPane.showMessageDialog(this, "APAGADO COM SUCESSO");
           
              }
              else{
              JOptionPane.showMessageDialog(this, "CANCELADO");
              }  
      }catch (SQLException ex) {
        
            Logger.getLogger(OC.class.getName()).log(Level.SEVERE, null, ex); 
      }
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void TabelaOCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaOCMouseClicked
TxtNumeroOC.setText(TabelaOC.getValueAt(TabelaOC.getSelectedRow(),0).toString()); 
TxtNumero.setText(TabelaOC.getValueAt(TabelaOC.getSelectedRow(),1).toString()); 
TxtCliente.setText(TabelaOC.getValueAt(TabelaOC.getSelectedRow(),2).toString());
TxtEndereco.setText(TabelaOC.getValueAt(TabelaOC.getSelectedRow(),3).toString());
TxtProduto.setText(TabelaOC.getValueAt(TabelaOC.getSelectedRow(),4).toString());
TxtStatus.setSelectedItem(TabelaOC.getValueAt(TabelaOC.getSelectedRow(),5).toString());
       // TODO add your handling code here:
    }//GEN-LAST:event_TabelaOCMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            Connection con =  (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pontovenda","root","acessonery");
            PreparedStatement p = con.prepareStatement(" update carga set id_pedido =?, cliente = ?, endereco = ?, itens =?, status =? where id_oc = ? ");
             
             //id não pode ser alterado
             
             p.setString(6,TxtNumeroOC.getText());
             p.setString(1,TxtNumero.getText());
             p.setString(2,TxtCliente.getText());                        
             p.setString(3,TxtEndereco.getText());
             p.setString(4,TxtProduto.getText());                       
             p.setString(5, (String) TxtStatus.getSelectedItem());
             
             p.execute();      
	     p.close();
             readJTable();
             limparCampos();
        
        } catch (SQLException ex) {
            Logger.getLogger(OC.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Dados Alterados Com Sucesso"); 
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   this.setExtendedState(MAXIMIZED_BOTH);         
    }//GEN-LAST:event_formWindowOpened

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Contrato frame = new Contrato();;
        frame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baixar;
    private javax.swing.JTable TabelaOC;
    private javax.swing.JTextField TxtCliente;
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtNumeroOC;
    private javax.swing.JTextPane TxtProduto;
    private javax.swing.JComboBox<String> TxtStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
