/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

//import java.util.Properties;

import java.util.Properties;
import javax.mail.Address;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

//import javax.mail.Address;
//import javax.mail.Message;
//import javax.mail.MessagingException;
////import javax.mail.PasswordAuthentication;
//import javax.mail.Session;
//import javax.mail.Transport;
//import javax.mail.internet.InternetAddress;
//import javax.mail.internet.MimeMessage;
//import javax.swing.JOptionPane;

/**
 *
 * @author alvaro
 */
public class EnviarEmail extends javax.swing.JFrame {

    /**
     * Creates new form EnviarEmail
     */
    public EnviarEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtEmail = new javax.swing.JTextField();
        TxtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Texto = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtAssunto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Destino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtEmail.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        TxtEmail.setText(" ");
        TxtEmail.setBorder(null);
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 170, 30));

        TxtSenha.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        TxtSenha.setBorder(null);
        jPanel1.add(TxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 79, 170, 30));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seu Email:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sua Senha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Destinatario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Texto.setColumns(20);
        Texto.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        Texto.setRows(5);
        Texto.setBorder(null);
        jScrollPane1.setViewportView(Texto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 250, 100));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Digite sua mensagem aqui:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Assunto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        TxtAssunto.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        TxtAssunto.setText(" ");
        TxtAssunto.setBorder(null);
        jPanel1.add(TxtAssunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/Enviar.png"))); // NOI18N
        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 370, 140, 40));

        Destino.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        Destino.setText(" ");
        Destino.setBorder(null);
        jPanel1.add(Destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 119, 170, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/18_wheeler_truck_1024x1024.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 250));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("nerysoftware@gmail.com");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/pdv.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Assunto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
               
            Properties props = new Properties();
          
            
            /** Parâmetros de conexão com servidor Gmail */
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.port", "465");
            
                
 
            //altenticação
            Session session = Session.getDefaultInstance(props,
                        new javax.mail.Authenticator() {
                         
                             @Override
                             protected PasswordAuthentication getPasswordAuthentication() 
                             {                   //estava dando erro devido ao gmail bloquear o acesso
                                   return new PasswordAuthentication(TxtEmail.getText(), TxtSenha.getText());
                             }
                        });
 
            /** Ativa Debug para sessão */
            session.setDebug(true);
 
            try {
 
                  Message message = new MimeMessage(session);
                  message.setFrom(new InternetAddress(TxtEmail.getText())); //Remetente
 
                  Address[] toUser = InternetAddress //Destinatário(s)
                             .parse(Destino.getText());  
 
                  message.setRecipients(Message.RecipientType.TO, toUser);
                  message.setSubject(TxtAssunto.getText());//Assunto
                  message.setText(Texto.getText());
                  
                  /**Método para enviar a mensagem criada*/
                  Transport.send(message);
                 
                 
                 
                JOptionPane.showMessageDialog(this, "Email enviado com sucesso!");
                
 
             } catch (MessagingException e) {
                 JOptionPane.showMessageDialog(this, "Erro ao enviar email!");  
                  throw new RuntimeException(e);
                 
            }
    }   

    
 public void EnviarHotmail(){;
     
     
          Properties props = new Properties();
            /** Parâmetros de conexão com servidor Hotmail */
            props.put("mail.transport.protocol", "smtp");
            props.put("mail.smtp.host", "smtp.live.com");
            props.put("mail.smtp.socketFactory.port", "587");
            props.put("mail.smtp.socketFactory.fallback", "false");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.port", "587");
            
           //altenticação
            Session session = Session.getDefaultInstance(props,
                        new javax.mail.Authenticator() {
                         
                             @Override
                             protected PasswordAuthentication getPasswordAuthentication() 
                             {
                                   return new PasswordAuthentication(TxtEmail.getText(), TxtSenha.getText());
                             }
                        });

            /** Ativa Debug para sessão */
            session.setDebug(true);

            try {

                  Message message = new MimeMessage(session);
                  message.setFrom(new InternetAddress(TxtEmail.getText())); //Remetente

                  message.setRecipients(Message.RecipientType.TO, 
                                    InternetAddress.parse(Destino.getText())); //Destinatário(s)
                  
                  message.setSubject(TxtAssunto.getText());//Assunto
                  message.setText(Texto.getText());
                  
                 
                  
                 
                  /**Método para enviar a mensagem criada*/
                  Transport.send(message);
                JOptionPane.showMessageDialog(this, "Email enviado com sucesso!");
                 

             } catch (MessagingException e) {
                 JOptionPane.showMessageDialog(this, "Erro ao enviar email!");  
                  throw new RuntimeException(e);
            }
  

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviarEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Destino;
    private javax.swing.JTextArea Texto;
    private javax.swing.JTextField TxtAssunto;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
